@startuml
!theme toy
skinparam linetype ortho

' --- STAR 1 : PAYROLL ---
package "Payroll Process" {

    entity "dim_employee" as DE1 <<Dim>> {
        * employee_key : INT64 [PK]
         name_hash : STRING
         start_date : DATE
         separation_date : DATE
         department_name : STRING
         pay_basis : STRING
         employment_status : STRING
    }
    entity "dim_agency" as DA1 <<Dim>> {
        * agency_key : INT64 [PK]
         agency_name : STRING
    }
    entity "dim_job_title" as DJT1 <<Dim>> {
        * job_title_key : INT64 [PK]
         job_title : STRING
    }
    entity "dim_calendar" as DC1 <<Dim>> {
        * id : STRING [PK]
         full_date : DATE
         year : INT64
         year_week : INT64
         year_day : INT64
         fiscal_year : INT64
         fiscal_qtr : INT64
         month : INT64
         month_name : STRING
         week_day : STRING
         day_name : STRING
         day_is_weekday : INT64
    }


    entity "fct_payroll" as FP <<Fact>> {
        * payroll_key : INT64 [PK]
        * employee_key : INT64 [FK]
        * agency_key : INT64 [FK]
        * job_title_key : INT64 [FK]
        * fiscal_year : INT64 [FK]
         hourly_rate : FLOAT64
         regular_pay : FLOAT64
         overtime_pay : FLOAT64
         cash_outs : FLOAT64
         retro_pay : FLOAT64
         other_pay : FLOAT64
         total_earnings : FLOAT64
         record_updated_at : DATE
    }

    FP }|--|| DE1
    FP }|--|| DA1
    FP }|--|| DJT1
    FP }|--|| DC1

}



@enduml