@startuml
!theme toy
skinparam linetype ortho

' --- STAR 1 : PAYROLL ---
package "Payroll Process" {
    entity "fct_payroll" as FP <<Fact>> {}
    entity "dim_employee" as DE1 <<Dim>>
    entity "dim_agency" as DA1 <<Dim>>
    entity "dim_job_title" as DJT1 <<Dim>>
    entity "dim_calendar" as DC1 <<Dim>>

    FP }|--|| DE1
    FP }|--|| DA1
    FP }|--|| DJT1
    FP }|--|| DC1
}

@enduml