@startuml
!theme toy
skinparam linetype ortho

' --- STAR 1 : PAYROLL ---
package "Payroll Process" {
    entity "fct_payroll" as FP <<Fact>> {
        * payroll_key 
        * employee_key 
        * agency_key 
        * job_title_key 
        * fiscal_year 
         hourly_rate 
         regular_pay 
         overtime_pay 
         cash_outs 
         retro_pay 
         other_pay 
         total_earnings 
         record_updated_at 
    }
    entity "dim_employee" as DE1 <<Dim>> {
        * employee_key 
         name_hash 
         start_date 
         separation_date 
         department_name 
         pay_basis
         employment_status
    }
    entity "dim_agency" as DA1 <<Dim>> {
        * agency_key 
         agency_name 
    }
    entity "dim_job_title" as DJT1 <<Dim>> {
        * job_title_key 
         job_title 
    }
    entity "dim_calendar" as DC1 <<Dim>> {
         * id  
         full_date 
         year 
         year_week 
         year_day 
         fiscal_year 
         fiscal_qtr 
         month 
         month_name 
         week_day 
         day_name 
         day_is_weekday
    }
    
    FP }|--|| DE1
    FP }|--|| DA1
    FP }|--|| DJT1
    FP }|--|| DC1
}

@enduml