@startuml
!theme toy
skinparam linetype ortho

' --- STAR 1 : PAYROLL ---
package "Payroll Process" {
    entity "fct_payroll" as FP <<Fact>> {
        * payroll_key 
        * employee_key 
        * agency_key 
        * job_title_key 
        * fiscal_year 
         hourly_rate 
         regular_pay 
         overtime_pay 
         cash_outs 
         retro_pay 
         other_pay 
         total_earnings 
         record_updated_at 
    }
    entity "dim_employee" as DE1 <<Dim>> {
        * employee_key 
         name_hash 
         start_date 
         separation_date 
         department_name 
    }
    entity "dim_agency" as DA1 <<Dim>> {
        * agency_key 
         agency_name 
    }
    entity "dim_job_title" as DJT1 <<Dim>> {
        * job_title_key 
         job_title 
         pay_basis 
    }
    entity "dim_calendar" as DC1 <<Dim>> {
         * id  
         full_date 
         year 
         year_week 
         year_day 
         fiscal_year 
         fiscal_qtr 
         month 
         month_name 
         week_day 
         day_name 
         day_is_weekday
    }
    
    FP }|--|| DE1
    FP }|--|| DA1
    FP }|--|| DJT1
    FP }|--|| DC1
}

' --- STAR 2 : EVENTS ---
package "Human Resources Process" {
    entity "fct_employment_events" as FE <<Fact>> {
        * event_key 
        * employee_key 
        * agency_key 
        * job_title_key 
        * fiscal_year 
         event_date 
         event_type 

    }
    entity "dim_employee" as DE2 <<Dim>> {
        * employee_key 
         name_hash 
         start_date 
         separation_date 
         department_name 
    }
    entity "dim_agency" as DA2 <<Dim>> {
        * agency_key 
         agency_name 
    }
    entity "dim_job_title" as DJT2 <<Dim>> {
        * job_title_key 
         job_title 
         pay_basis 
    }
    entity "dim_calendar" as DC2 <<Dim>> {
         * id 
         full_date 
         year 
         year_week 
         year_day 
         fiscal_year 
         fiscal_qtr 
         month 
         month_name 
         week_day 
         day_name 
         day_is_weekday
    }
    FE }|--|| DE2
    FE }|--|| DA2
    FE }|--|| DJT2
    FE }|--|| DC2
}

' --- STAR 3 : STATS ---
package "Reporting Process" {
    entity "fct_agency_stats" as FS <<Fact>> {
        * agency_stats_key 
        * agency_key 
        * fiscal_year 
         total_payroll_cost 
         total_overtime_pay 
         avg_salary 
         count_hires 
         count_separations 
         count_employees 
    }
    entity "dim_agency" as DA3 <<Dim>> {
        * agency_key 
         agency_name 
    }   
    entity "dim_calendar" as DC3 <<Dim>> {
         * id
         full_date 
         year 
         year_week 
         year_day 
         fiscal_year 
         fiscal_qtr 
         month 
         month_name 
         week_day 
         day_name 
         day_is_weekday
    }

    FS }|--|| DA3
    FS }|--|| DC3
}

@enduml